site_name: AGEO Platform
site_url: https://ageoplatform.eu/
site_description: >-
  A project funded by INTERREG ATLANTIC AREA
# repo_name: ...
# repo_url: ...
copyright: AGEO Atlantic



nav:
  - Introduction: 
    - Intro: index.md
    - Contribute: introduction/contribute.md
  - Event Reporting:
    - Monitor Event: reporting/report_event.md
    - Quick Monitor: reporting/quick_report.md
  - Event Management:
    - Introduction: event_management/event_management.md
    - Map View: event_management/map_view.md
    - Table View: event_management/table_view.md
  - User Management:
    - Introduction: user/intro.md
    - Admin: user/admin.md  
    - Manager: user/manager.md
    - API User: user/apiuser.md
    - Anonymous: user/anonymous.md
  - DB Schema:
    - User: dbschema/user.md
    - Event: dbschema/event.md
  - Educational Content: education.md

theme:
  name: material
  logo: assets/logo-icon-white.png
  favicon: assets/logo-icon-white.png
  palette:
    scheme: default
    primary: light blue
    accent: green
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.follow

markdown_extensions:
- admonition
- attr_list
- md_in_html
- pymdownx.details
- pymdownx.superfences
plugins:
  - glightbox